### ISSUE TITLE
Web Interface Source Code

### ISSUE THREAD

**Issue by karlbaillie** [mouday/spider-admin-pro#1]
I'm trying to contribute English translation, however, the source code for the web interface isn't publicly available.

The documentation points me to `https://github.com/mouday/spider-admin-pro-web`, though I get 404.

Please can you provide the Vue code to facilitate this?

**Comment by mouday** [comment]
I add you into web project manager list, now you can visit this project 👍 
https://github.com/mouday/spider-admin-pro-web

**Comment by 635168775** [comment]
Please can you provide the Vue code to facilitate this?

你好，请问如何访问spider-admin-pro-web？谢谢！

**Comment by pinkonio** [comment]
> I add you into web project manager list, now you can visit this project 👍
> https://github.com/mouday/spider-admin-pro-web

I  want to be a participant too。

**Comment by mouday** [comment]
> > I add you into web project manager list, now you can visit this project 👍
> > https://github.com/mouday/spider-admin-pro-web
> 
> I want to be a participant too。

now, you can access web project.
