### ISSUE TITLE
Cannot pickle a ZoneInfo file from a file stream.

### ISSUE THREAD

**Issue by hstking** [mouday/spider-admin-pro#10]
配置完成后，修改了scrapy.cfg文档，并使用scrapyd-deploy demo命令，上传并布置好了爬虫。手动运行没问题，但在部署定时任务时，总是出现"Cannot pickle a ZoneInfo file from a file stream."提示，这是为什么？

**Comment by mouday** [comment]
应该是时间模块有问题，你是在docker上运行的吗？

**Comment by hstking** [comment]
是的，用docker运行的。毕竟部署起来比较方便。那应该怎么修改呢？在docker上添加-e TZ参数吗？




发自我的手机


-------- 原始邮件 --------
发件人： mouday ***@***.***>
日期： 2023年6月12日周一 10:15
收件人： mouday/spider-admin-pro ***@***.***>
抄送： hstking ***@***.***>, Author ***@***.***>
主 题： Re: [mouday/spider-admin-pro] Cannot pickle a ZoneInfo file from a file stream. (Issue #10)

应该是时间模块有问题，你是在docker上运行的吗？

―

**Comment by mouday** [comment]
项目中的 [https://github.com/mouday/spider-admin-pro/blob/master/Dockerfile](https://github.com/mouday/spider-admin-pro/blob/master/Dockerfile) 里边有

```bash
cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
```

**Comment by hstking** [comment]
在docker中添加了 -e TZ=Asia/Shanghai参数，进入scrapyd容器和spider-admin-pro容器中执行了cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime命令，重启了这两个容器。也重新上传了爬虫。还是同样的提示。

**Comment by mouday** [comment]
解决了吗？我找到一个方法，试试看：https://www.jianshu.com/p/88aaef3982a9

**Comment by hstking** [comment]
已解决，谢谢。



***@***.***
 
From: mouday
Date: 2023-09-22 13:49
To: mouday/spider-admin-pro
CC: hstking; Author
Subject: Re: [mouday/spider-admin-pro] Cannot pickle a ZoneInfo file from a file stream. (Issue #10)
解决了吗？我找到一个方法，试试看：https://www.jianshu.com/p/88aaef3982a9

**Comment by nicedouble** [comment]
@hstking 怎么结局的

**Comment by ThinkerWen** [comment]
> @hstking 怎么结局的

手动进到docker容器里，修改/app/spider_admin_pro/service/schedule_service.py
在 scheduler.add_job函数的参数里增加一行（根据自己时区修改）：
`timezone=pytz.timezone('Asia/Shanghai'),`
别忘了`import pytz`
然后重启容器就好了
![image](https://github.com/mouday/spider-admin-pro/assets/59362976/de1aa355-40a8-4ea8-be4d-5f64fd404e3f)
